export const USER_STATE_CHANGED = 'USER_STATE_CHANGED';
export const ADDED_AGENTS = 'ADDED_AGENTS';
export const CURRENT_AGENT = 'CURRENT_AGENT';
export const CURRENT_PROPERTIES = 'CURRENT_PROPERTIES'
export const AGENT_PROPERTY = 'AGENT_PROPERTY'
export const AGENT_BY_ID = 'AGENT_BY_ID'
export const AGENT_PROPERTY_BY_ID = 'AGENT_PROPERTY_BY_ID'